version: 0.2

env:
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
    JEKYLL_ENV: production
  parameter-store:
    SITE_BUCKET_URL: "/codebuild/jonkyops.com/siteBucketUrl"
    DISTRIBUTION_ID: "/codebuild/jonkyops.com/distributionId"
    ALGOLIA_API_KEY: "/codebuild/jonkyops.com/algoliaApiKey"

phases:
  install:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
  post_build:
    commands:
      - bundle exec jekyll algolia
      - aws s3 sync --delete _site/ s3://$SITE_BUCKET_URL/
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
