version: 0.2

env:
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
  parameter-store:
    SITE_BUCKET_URL: "siteBucketUrl"
    DISTRIBUTION_ID: "distributionId"

phases:
  install:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
  post_build:
    commands:
      - aws s3 sync --delete _site/ s3://$SITE_BUCKET_URL/
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
