version: 0.2

phases:
  install:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
  post_build:
    commands:
      - aws s3 sync --delete _site/ s3://jonkyops.com/
      - aws cloudfront create-invalidation --distribution-id E382WQ7KSXGBPG --paths '/*'
